services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      RESERVATION_TIMEOUT: 600
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: sales
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
